spring:
  datasource:
    # 数据库驱动类名
    driverClassName: org.mariadb.jdbc.Driver
    # 数据库连接URL
    url: jdbc:mariadb://localhost:3306/test
    # 数据库连接用户名
    username: root
    # 数据库连接密码
    password: 123456
    # 数据库连接池配置
    hikari:
      # 数据库连接超时时间（毫秒）
      connectionTimeout: 600000
      # 数据库连接池最大连接数
      maximumPoolSize: 10
      # 数据库连接池最小空闲连接数
      minimumIdle: 5
      # 数据库连接池最大空闲时间（毫秒）
      idleTimeout: 500000
