spring:
  application:
    name: vt-boot-example-multi-datasource
  thymeleaf:
    check-template-location: false
  config:
    import: classpath:datasource.yaml,classpath:mybatisplus.yaml,classpath:logback.yaml,classpath:vt-mq.yaml


server:
  port: 9083
