spring:
  application:
    name: vt-boot-example-single-datasource
  thymeleaf:
    check-template-location: false
  config:
    import: classpath:datasources.yaml,classpath:mybatisplus.yaml,classpath:logback.yaml

server:
  port: 9082
